### PR TITLE
Feature nav

### PR DESCRIPTION
**Pull request by rashidaysher**
ready for merging'

### CODE REVIEW

**Review by git-ahi — APPROVED** [review]

**Comment by git-ahi** [comment]
Aisha there's a major conflict on your pull request, I'm unable to solve it from the browser. Try to avoid changing the app.component file unless you really have to.

**Comment by rashidaysher** [comment]
merge request

**Review by git-ahi — APPROVED** [review]
Thank you Aisha

**Comment by rashidaysher** [comment]
kelvin, do we have a slide? if not send me the document i make it. my slack
can't send or receive messages

**Pull request merged**
